import './globals.css'
import {Inter} from 'next/font/google'
import Link from 'next/link'

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


export default function RootLayout({children}) {
    return (

        <html lang="en">
        <body className={inter.className}>
        <nav>
            <Link className="pr-5" href="/tiptap">tiptap</Link>

            <Link className="pr-5" href="/lexical">lexical</Link>

            <Link className="pr-5" href="/suneditor">suneditor</Link>

            <Link className="pr-5" href="/quill">quill</Link>

            <Link className="pr-5" href="/handlechick">handlechick</Link>

            <Link className="pr-5" href="/fromtodo">fromtodo</Link>
            <Link className="pr-5" href="/from">from</Link>
            <Link href="/">home</Link>
        </nav>
        {children}</body>
        </html>
    )
}
